batch_type: numel
batch_bins: 8000000
accum_grad: 1
max_epoch: 10
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

freeze_param: ["decoder", "encoder.encoders.w2v_encoder.w2v_model",]

input_size: 768
encoder: wav2vec_ctc
encoder_conf:
    output_size: 32
    normalize_before: true
    freeze_finetune_updates: 0
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_100h_new.pt
    w2v_dir_path: ./downloads/wav2vec_pretrained_models

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.01
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 20000

ctc_conf:
    ctc_type: fairctc

unused_parameters: true

frontend: null

normalize: null

specaug: null