batch_type: numel
batch_bins: 1400000
accum_grad: 8
max_epoch: 35
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1

freeze_param: ["decoder",]

input_size: 768
encoder: wav2vec_ctc
encoder_conf:
    output_size: 32
    normalize_before: true
    freeze_finetune_updates: 0
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
    w2v_dir_path: ./downloads/wav2vec_pretrained_models

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.0003 # 0.00002 
# scheduler: warmuplr
# scheduler_conf:
#     warmup_steps: 1600
scheduler: warmuplr
scheduler_conf:
    init_lr_scale: 0.01
    final_lr_scale: 0.05
    warmup_steps:
    hold_steps:
    decay_steps:

ctc_conf:
    ctc_type: fairctc

frontend: null

normalize: fair_like_norm

specaug: null

unused_parameters: true