batch_type: numel
batch_bins: 1400000
accum_grad: 10 # 3090 4 GPU settings
max_epoch: 20
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - cer_ctc
    - min
keep_nbest_models: 1

freeze_param: [
    "decoder",
]

input_size: 1024
encoder: wav2vec_ctc
encoder_conf:
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
    w2v_dir_path: ./downloads/wav2vec_pretrained_models
    output_size: 32
    apply_mask: true
    mask_prob: 0.5
    mask_channel_prob: 0.5
    mask_channel_length: 64
    layerdrop: 0.1
    activation_dropout: 0.1
    feature_grad_mult: 0.0
    freeze_finetune_updates: 10000

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00003
scheduler: tristagelr
scheduler_conf:
    init_lr_scale: 0.01
    final_lr_scale: 0.05
    warmup_steps: 8000
    hold_steps: 32000
    decay_steps: 40000

ctc_conf:
    ctc_type: fairctc

frontend: null

normalize: fair_like_norm

specaug: null

unused_parameters: true

#############################
##### semi task related #####
#############################

init_param: 
    - downloads/wav2vec_pretrained_models/wav2vec_vox_100h_asml_new.pt:encoder:encoder

pis_ratio: 0.5